import 'clouds_model.dart';
import 'coords_model.dart';
import 'main_model.dart';
import 'sys_model.dart';
import 'weather_weather_model.dart';
import 'wind_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class WeatherModel {
/*
{
  "coord": {
    "lon": 139,
    "lat": 35
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 298.32,
    "feels_like": 299.32,
    "temp_min": 298.32,
    "temp_max": 298.32,
    "pressure": 1008,
    "humidity": 93
  },
  "visibility": 10000,
  "wind": {
    "speed": 0.45,
    "deg": 219,
    "gust": 1.34
  },
  "clouds": {
    "all": 97
  },
  "dt": 1659462183,
  "sys": {
    "type": 2,
    "id": 2019346,
    "country": "JP",
    "sunrise": 1659470065,
    "sunset": 1659519956
  },
  "timezone": 32400,
  "id": 1851632,
  "name": "Shuzenji",
  "cod": 200
} 
*/

  WeatherModelCoord? coord;
  List<WeatherModelWeather?>? weather;
  String? base;
  WeatherModelMain? main;
  int? visibility;
  WeatherModelWind? wind;
  WeatherModelClouds? clouds;
  int? dt;
  WeatherModelSys? sys;
  int? timezone;
  int? id;
  String? name;
  int? cod;

  WeatherModel({
    this.coord,
    this.weather,
    this.base,
    this.main,
    this.visibility,
    this.wind,
    this.clouds,
    this.dt,
    this.sys,
    this.timezone,
    this.id,
    this.name,
    this.cod,
  });
  WeatherModel.fromJson(Map<String, dynamic> json) {
    coord = (json['coord'] != null)
        ? WeatherModelCoord.fromJson(json['coord'])
        : null;
    if (json['weather'] != null) {
      final v = json['weather'];
      final arr0 = <WeatherModelWeather>[];
      v.forEach((v) {
        arr0.add(WeatherModelWeather.fromJson(v));
      });
      weather = arr0;
    }
    base = json['base']?.toString();
    main =
        (json['main'] != null) ? WeatherModelMain.fromJson(json['main']) : null;
    visibility = json['visibility']?.toInt();
    wind =
        (json['wind'] != null) ? WeatherModelWind.fromJson(json['wind']) : null;
    clouds = (json['clouds'] != null)
        ? WeatherModelClouds.fromJson(json['clouds'])
        : null;
    dt = json['dt']?.toInt();
    sys = (json['sys'] != null) ? WeatherModelSys.fromJson(json['sys']) : null;
    timezone = json['timezone']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    cod = json['cod']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['weather'] = arr0;
    }
    data['base'] = base;
    if (main != null) {
      data['main'] = main!.toJson();
    }
    data['visibility'] = visibility;
    if (wind != null) {
      data['wind'] = wind!.toJson();
    }
    if (clouds != null) {
      data['clouds'] = clouds!.toJson();
    }
    data['dt'] = dt;
    if (sys != null) {
      data['sys'] = sys!.toJson();
    }
    data['timezone'] = timezone;
    data['id'] = id;
    data['name'] = name;
    data['cod'] = cod;
    return data;
  }
}
